### ISSUE TITLE
Auto-complete does not work

### ISSUE THREAD

**Issue by rajanjana** [eyala/pig-eclipse#6]
Hi Eyal,

First of all thanks for providing this plugin. I installed the plugin on -
OSX Yosemite - 10.10.5
Eclipse Luna - 4.4.2

Post installation, the plugin recognizes pig files, however auto-complete does not seem to work using (ctrl + space). Am I missing something ? Does the auto-complete only work for specific language constructs ?

Thanks in advance.

**Comment by eyala** [comment]
Hi rajanjana-

I'm not sure what you mean by "specific language constructs". At the very least, Pig-Eclipse should always offer you the reserved words of Pig when you activate auto-complete. I've never tried it on OSX, but maybe we can figure out why it isn't working and fix it. Can you try doing the following?

Open the Error Log view, and change the filters there to display everything. Then try auto-complete and copy-paste the logs here so I can see them. Try something else, too, like F3 or hovering on a UDF to see what happens then. I'm hoping the logs will provide some insight into why it isn't working.

**Comment by rajanjana** [comment]
Hi Eyal,

Sorry, by language constructs I wanted to say does it work for specific keywords or reserved words only ?
Pressing F3 on a UDF work perfect by opening the UDF.

Here is the log when I typed "Loa" and pressed ctrl+space -

!ENTRY org.eclipse.ui 4 0 2015-10-08 14:03:02.146
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.Error: Unresolved compilation problem: 

```
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:62)
at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1098)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1504)
at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1500)
at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:496)
at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1060)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5730)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:68)
at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:594)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5640)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2105)
at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2329)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5702)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5139)
at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5288)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3666)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

Caused by: java.lang.Error: Unresolved compilation problem: 

```
at org.apache.pig.contrib.eclipse.utils.RegexUtils.findImports(RegexUtils.java:45)
at org.apache.pig.contrib.eclipse.utils.WorkspaceSearcher.findRecursiveImports(WorkspaceSearcher.java:112)
at org.apache.pig.contrib.eclipse.editors.PigContentAssistant.computeCompletionProposals(PigContentAssistant.java:83)
at org.eclipse.jface.text.contentassist.ContentAssistant$5.run(ContentAssistant.java:1904)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1902)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:499)
at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1720)
at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:932)
at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:82)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:80)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
... 60 more
```

**Comment by rajanjana** [comment]
This is the Java version I am using -

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by eyala** [comment]
Are you using version 1.1.1?

I tried switching to Java 8 (normally I use 7) but couldn't replicate it. I use Windows and Ubuntu, though - I'll see if I can find someone with a Mac to let me investigate with their computer.

**Comment by eyala** [comment]
I can replicate this problem on Macs. Building Pig-Eclipse on a Mac will solve the problem. I need to verify that the resulting binary also works on Windows and Linux, and then I will upload it to our update site.

**Comment by stephenh** [comment]
FWIW I'm getting this stack trace as well, in Eclipse Neon (4.6) on Ubuntu with Java 8 as my runtime:

```
java.lang.Error: Unresolved compilation problem: 

    at org.apache.pig.contrib.eclipse.utils.RegexUtils.findImports(RegexUtils.java:45)
    at org.apache.pig.contrib.eclipse.utils.WorkspaceSearcher.findRecursiveImports(WorkspaceSearcher.java:112)
    at org.apache.pig.contrib.eclipse.editors.PigContentAssistant.computeCompletionProposals(PigContentAssistant.java:83)
    at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:1931)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1928)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:565)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:560)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:494)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:487)
    at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1747)
    at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:939)
    at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:84)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:81)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
    at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:54)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1605)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1339)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1378)
    at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:764)
    at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3457)
    at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:801)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2000)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5819)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5490)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4141)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

I'm fairly surprised, because I would have thought "Unresolved compilation problem" would have been an error at compile time when the plugin binary was built.

**Comment by eyala** [comment]
@stephenh It doesn't cause a problem at compile time, because it works with the Java version I used when compiling. I guess there is a mismatch with the (older) Java version I used to build the jar, and newer versions. You can solve this by building the plugin yourself, and I'll try to build it with a newer version as soon as I can - I'm just worried about getting the opposite problem (that it will stop working with older Java versions)

**Comment by stephenh** [comment]
Hi Eyal,

Huh. I'm surprised it works for you, because this error "Unresolved compilation problem" AFAIU is not generated from the Java Runtime itself (e.g. like usual runtime errors like method missing or class mismatch error or what not), but instead is specifically interested by the Eclipse compiler at build-time:

http://stackoverflow.com/questions/1124788/java-unresolved-compilation-problem

Where Eclipse is saying "well, I can't compile this method, but I'm going to produce a valid .class file anyway, which just fails at runtime".

I can try this locally myself, but I don't see any build instructions in the README, nor maven poms or gradles or what not; are you using Eclipse to produce the artifacts? (If so, that lends credence to the "ecj inserted this compilation error at build-time" theory.)

I tried to import the projects into my Eclipse install that has the plugin development packages, and I could import "org.apache.pig.contrib.eclipse" but not the "org.apache.pig.contrib.eclipse.feature". Perhaps I'm missing something obvious...

**Comment by eyala** [comment]
@stephenh 

I built a new version and tested that it was working on a friend's Mac, then put it into a new release - you can try updating and see if it works for you now. I looked at the question you linked, and tried checking the checkbox to fail a build if one of the warnings there is triggered - but that didn't happen. I'm guessing that building Pig-Eclipse on Ubuntu's OpenJDK, version 6, just isn't compatible with a modern Mac running Java 8.

I really hope the problem is solved now.

As for building a Pig-Eclipse binary - yes, I am using Eclipse to do so, and it's an "Eclipse" project, not Maven or Gradle - I added instructions in the [wiki](https://github.com/eyala/pig-eclipse/wiki/Setting-up-a-development-environment#creating-an-update-site-binaries). If what I did didn't solved the problem for you, try building your own version.

Sorry about all the time it's taken me to get to this - it's been in my mind, and I really wanted to be more responsive ... but it really didn't work out that way.

**Comment by stephenh** [comment]
@eyala nice, it works! I've spent a few minutes poking around, but auto-completely is definitely popping up now. I'll play with it more as I work on things.

> I added instructions in the wiki.

Great, thanks!

> Sorry about all the time it's taken me to get to this - it's been in my mind, and I really wanted to
> be more responsive ... but it really didn't work out that way.

Hehe, definitely np, understood this is open source/hobby project, and that's just how things go.

Thanks for your time!

**Comment by eyala** [comment]
@stephenh

make sure to tell all your Pig-and-Mac-using friends that this issue is solved :-)
